### ISSUE TITLE
CSV-Import

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D.#17]
Wäre es möglich, dass man eine CSV-Datei herunterladen kann, welche als Vorlage für den Import neuer Produkte geeignet ist. Und diese Datei dann ausgefüllt nochzuladen. Idealerweise mit einer Importvorschau, welcher man zustimmen kann bzw. abbrechen.
Danke, das Abenteuerteam

**Comment by oliveraustria** [comment]
Wir glauben dieses Feature ist besonders interessant, wenn größere Mengen neuer Inventargegenstände dazu kommen. (Es müsste aber auch der Nutzung im Vorfeld evaluiert werden.)
@GLSteiner Was meinst du?

**Comment by GLSteiner** [comment]
Ich überlege noch...

Auf jeden Fall mal akut, für euch:

`Nummer, Name, Status, Preis, Kategorie, Lagerplatz, LetztenNutzungsjahr `

Ich sollte jede Excel Tabelle, CSV, etc.. dank `Strg H` für die Datenbank vorbereiten können - Ich weiß nicht wie viele neue Bereiche noch kommen, dass sich die Entwicklung einer benutzerfreundlichen Lösung auszahlt. Wie oft würdet ihr diese Funktion den brauchen?

**Comment by GLSteiner** [comment]
Ist natürlich nicht das selbe, aber auch praktisch:

https://github.com/Ferienhort/F.H.I.E.L.D/wiki/PowerInfo:-Clientseitig#copy

**Comment by GLSteiner** [comment]
Scheint alles sehr weit weg zu sein, für den Einzelfall ist import über PHPMyAdmin möglich. Größere Lösung wird es nicht geben
