### ISSUE TITLE
Einfache Eingabe für Tablet erstellen

### ISSUE THREAD

**Issue by janniac2** [Ferienhort/F.H.I.E.L.D.#33]
While opening Scanned QR Website
   if Device=Samsung Galaxy Tab (MAC address Verknüpfung?)
then open
   Simplified UI with auto login to SAMSUNG_TAB account, with rights only to verleihen/retournieren article for a specific student number

and show
   full screen numpad for student number, because typing in numbers on integrated Samsung Galaxy Tab Keyboard is hard as hell

if Article=ausgeliehen
   show banner "ARTIKEL AUSGELIEHEN, RÜCKGABE"
   bgcolor=red
else
   bgcolor=green
end if
end if

**Comment by GLSteiner** [comment]
OK, serious question...

warum musst ihr unbedingt das Galaxy Tab verwenden?

**Comment by GLSteiner** [comment]
Hat sich nach telefonat erubrigt!
