### ISSUE TITLE
Neuen Status: Gefehlt bei letzter Inventur

### ISSUE THREAD

**Issue by janniac2** [Ferienhort/F.H.I.E.L.D.#36]
If Part_Status=OK then
if Hat_gefehlt_bei_letzter_Inventur=Ja then
set Part_Status GRÜN-GELB: Gefehlt bei letzter Inventur
end if
end if

if Part_Status=GRÜN-GELB: Gefehlt bei letzter Inventur then
if scan=1 
' item has been scanned
set Part_Status=OK
end if
end if

Zum erhöhen der Aufmerksamkeit auf vermeintlich verlorene Teile.

**Comment by GLSteiner** [comment]
Abgesehen von der Automatik, was ist der Unterschied zu verloren?
Ware es nicht sinnvoller einfach alles Fehlende automatisch als OK anzuzeigen, sollte es gescannt werden?

ODER

Geht es dir hier um ein Wahnzeichen (rufzeichen o.a.) wenn etwas bei der letzten Inventur nicht da war aber immernoch als OK eingetragen ist...

**Comment by GLSteiner** [comment]
Neue Info: Wir haben bis jetzt kaum eine Invetur die mehr als 60% des Inventars gesacnnat hat.

Die ganzen Wahnzeichen wurden vermutlich sehr schnell inflationaer werden, deshalb eher nicht.
